---
name: Release to Ansible Galaxy

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: galaxy
        uses: ucomesdag/galaxy-action@main
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
