---
name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '2 2 2 * *'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: ucomesdag/molecule-action@main
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "alpine"
            tag: "edge"
          - image: "alpine"
            tag: "latest"
          - image: "amazonlinux"
            tag: "latest"
          - image: "archlinux"
            tag: "latest"
          - image: "centos"
            tag: "latest"
          - image: "centos"
            tag: "stream8"
          - image: "debian"
            tag: "latest"
          - image: "debian"
            tag: "buster"
          - image: "fedora"
            tag: "rawhide"
          - image: "fedora"
            tag: "latest"
          - image: "fedora"
            tag: "34"
          - image: "fedora"
            tag: "33"
          - image: "opensuse"
            tag: "latest"
          - image: "rhel"
            tag: "latest"
          - image: "rocky"
            tag: "latest"
          - image: "rpi-os"
            tag: "latest"
          - image: "ubuntu"
            tag: "jammy"
          - image: "ubuntu"
            tag: "latest"
          - image: "ubuntu"
            tag: "bionic"

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: ucomesdag/molecule-action@main
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
